"""empty message

Revision ID: 38f878ff6b03
Revises: 5348ed3bc065
Create Date: 2021-09-03 12:45:38.266858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f878ff6b03'
down_revision = '5348ed3bc065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteringpoint_owner',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['users.subject'], ),
    sa.PrimaryKeyConstraint('gsrn')
    )
    op.create_index(op.f('ix_meteringpoint_owner_begin'), 'meteringpoint_owner', ['begin'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_end'), 'meteringpoint_owner', ['end'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_gsrn'), 'meteringpoint_owner', ['gsrn'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_subject'), 'meteringpoint_owner', ['subject'], unique=False)
    op.create_unique_constraint(None, 'meteringpoint_delegate', ['gsrn', 'subject'])
    op.create_unique_constraint(None, 'token', ['opaque_token'])
    op.create_unique_constraint(None, 'users', ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'token', type_='unique')
    op.drop_constraint(None, 'meteringpoint_delegate', type_='unique')
    op.drop_index(op.f('ix_meteringpoint_owner_subject'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_gsrn'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_end'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_begin'), table_name='meteringpoint_owner')
    op.drop_table('meteringpoint_owner')
    # ### end Alembic commands ###
