"""empty message

Revision ID: 65192142aba0
Revises: 
Create Date: 2021-09-08 11:25:22.505836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65192142aba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteringpoint_delegate',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('gsrn', 'subject'),
    sa.UniqueConstraint('gsrn', 'subject')
    )
    op.create_index(op.f('ix_meteringpoint_delegate_gsrn'), 'meteringpoint_delegate', ['gsrn'], unique=False)
    op.create_index(op.f('ix_meteringpoint_delegate_subject'), 'meteringpoint_delegate', ['subject'], unique=False)
    op.create_table('meteringpoint_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meteringpoint_owner_begin'), 'meteringpoint_owner', ['begin'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_end'), 'meteringpoint_owner', ['end'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_gsrn'), 'meteringpoint_owner', ['gsrn'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_id'), 'meteringpoint_owner', ['id'], unique=False)
    op.create_index(op.f('ix_meteringpoint_owner_subject'), 'meteringpoint_owner', ['subject'], unique=False)
    op.create_table('token',
    sa.Column('opaque_token', sa.String(), nullable=False),
    sa.Column('internal_token', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('issued', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('issued < expires'),
    sa.PrimaryKeyConstraint('opaque_token'),
    sa.UniqueConstraint('opaque_token')
    )
    op.create_index(op.f('ix_token_opaque_token'), 'token', ['opaque_token'], unique=False)
    op.create_index(op.f('ix_token_subject'), 'token', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('subject'),
    sa.UniqueConstraint('subject')
    )
    op.create_index(op.f('ix_users_subject'), 'users', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_subject'), table_name='token')
    op.drop_index(op.f('ix_token_opaque_token'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_meteringpoint_owner_subject'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_id'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_gsrn'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_end'), table_name='meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_owner_begin'), table_name='meteringpoint_owner')
    op.drop_table('meteringpoint_owner')
    op.drop_index(op.f('ix_meteringpoint_delegate_subject'), table_name='meteringpoint_delegate')
    op.drop_index(op.f('ix_meteringpoint_delegate_gsrn'), table_name='meteringpoint_delegate')
    op.drop_table('meteringpoint_delegate')
    # ### end Alembic commands ###
