name: Update environment chart

inputs:
  update_env_token:
    description: The token used to update base env
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: Get chart name
      id: get-chart-name
      uses: ./.github/actions/yaml-get
      with:
        yaml_file: chart/Chart.yaml
        yaml_path: name

    - name: Update helm chart in base env
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        workflow: Update helm chart version
        token: ${{ inputs.update_env_token }}
        inputs: |
          { 
            "name": "${{ steps.get-chart-name.outputs.result }}", 
            "repoURL": "${{ github.repositoryUrl }}", 
            "targetRevision": "${{ github.event.pull_request.head.ref }}", 
            "path": "chart" 
          }
        ref: main
        repo: Chrisbh/eo-base-environment
